apiVersion: v1
kind: Service
metadata:
  name: venecash-app-service
spec:
#  type: NodePort
  type: LoadBalancer
  selector:
    app: venecash-app
  ports:
  - port: 4174
    targetPort: 4174
#    nodePort: 30001